### ISSUE TITLE
Facts

### ISSUE THREAD

**Issue by TheFixerDevelopment** [DuooIncc/CPEParticle#1]
Hey, just going to say. What's the point in putting API support for 3.0.0-ALPHA12 and 3.0.0? You do realize those API's support are different, and are not backwards compatibility due to the new scheduler updates? You better change it before people start judging you about it. Also, it's best to bump all API's to 3.0.0, and code as well. I'll need to recheck and see what needs changing. I might do a PR, but not sure yet. Thanks.

**Comment by DuooIncc** [comment]
Ok. Thanks for the information on that. Ill make sure that i check api's in future.

**Comment by TheFixerDevelopment** [comment]
Okay, thanks for understanding! I’ll close this issue now!

**Comment by RyanTheOwner** [comment]
For your teaspoon plugin can you make it a normal zip please
